### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by alexwh** [Eternita-S/TextAdvance#7]
Had the following error appear in chat after completing the shb role quest "Freedom from Privilege". I picked the first dialogue option, if that matters.

```
[1:14]Object reference not set to an instance of an object.   at TextAdvance.TextAdvance.TickQuestComplete() in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 164
   at TextAdvance.TextAdvance.Tick(Framework framework) in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 135
```
/xllog from around this time:
```
01:13:40.035 | INF [NoSoliciting] Filtered chat message (custom): You have left the sanctuary.
--------------------------------
01:13:40.361 | INF [NoSoliciting] Filtered chat message (custom): You have entered a sanctuary.
--------------------------------
01:14:10.101 | INF [NoSoliciting] Filtered chat message (custom): “Freedom from Privilege” complete!
--------------------------------
01:14:13.327 | INF [SimpleTweaksPlugin] Add ItemLevel to CharacterInspect
--------------------------------
01:14:15.374 | INF [NoSoliciting] Filtered chat message (custom): “The Hunter's Legacy” accepted.
--------------------------------
01:14:24.535 | INF [NoClippy] Ignored reducing server cast lock of 2100 ms
--------------------------------
01:14:25.599 | INF [Dalamud.LoadingImage] toLoadingTerri: 814
--------------------------------
01:14:25.599 | INF [Dalamud.LoadingImage] LoadIcon: 122027 detected for r:354 with toLoadingTerri:814
--------------------------------
01:14:25.599 | INF [Dalamud.LoadingImage] Replacing icon for territory 354
--------------------------------
01:14:25.609 | INF [Dalamud.LoadingImage] unitbase: 20F15C85300 visible: True
--------------------------------
01:14:25.609 | INF [Dalamud.LoadingImage] unishort: 20F15C85C30 visible: False
--------------------------------
01:14:26.336 | INF [NoSoliciting] Filtered chat message (custom): You have left the sanctuary.
--------------------------------
01:14:26.817 | INF [NoSoliciting] Filtered chat message (custom): You have entered a sanctuary.
--------------------------------
01:14:30.562 | INF [NoClippy] Ignored reducing server cast lock of 100 ms
--------------------------------
01:14:34.331 | INF [NoSoliciting] Filtered chat message (custom): You have left the sanctuary.
--------------------------------
01:14:56.899 | INF [SimpleTweaksPlugin] Add ItemLevel to CharacterInspect
--------------------------------
01:14:58.570 | INF [NoSoliciting] Filtered chat message (custom): “The Hunter's Legacy” objective fulfilled!
{ } [ Send ]
```

**Comment by Eternita-S** [comment]
Hello!
Thank you for reporting the error.
It will be fixed in next update.
The error is handled and is not critical so you may feel free to continue using the plugin in meantime.

**Comment by Eternita-S** [comment]
should be properly fixed now
